// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlNhI026x1b_HuhhVSTUtt7s65ID3mmVc',
    appId: '1:690914403970:web:4b9fdcc56228bd3115369b',
    messagingSenderId: '690914403970',
    projectId: 'mindmend-86949',
    authDomain: 'mindmend-86949.firebaseapp.com',
    storageBucket: 'mindmend-86949.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPT8tvU-eRWlsiml8eqautNhbKdBgv9Jw',
    appId: '1:690914403970:android:53f0f21d3c386fd515369b',
    messagingSenderId: '690914403970',
    projectId: 'mindmend-86949',
    storageBucket: 'mindmend-86949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSwXFEyvhtxN89cjg2LUjCMDaui4VRafc',
    appId: '1:690914403970:ios:a2ae0a1455dd271615369b',
    messagingSenderId: '690914403970',
    projectId: 'mindmend-86949',
    storageBucket: 'mindmend-86949.firebasestorage.app',
    iosBundleId: 'com.example.mindmend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSwXFEyvhtxN89cjg2LUjCMDaui4VRafc',
    appId: '1:690914403970:ios:a2ae0a1455dd271615369b',
    messagingSenderId: '690914403970',
    projectId: 'mindmend-86949',
    storageBucket: 'mindmend-86949.firebasestorage.app',
    iosBundleId: 'com.example.mindmend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlNhI026x1b_HuhhVSTUtt7s65ID3mmVc',
    appId: '1:690914403970:web:32af20e705145f6715369b',
    messagingSenderId: '690914403970',
    projectId: 'mindmend-86949',
    authDomain: 'mindmend-86949.firebaseapp.com',
    storageBucket: 'mindmend-86949.firebasestorage.app',
  );
}
